# Dockerfile for realm based alpine
# Copyright (C) 2025 5points
# Reference URL:
# https://github.com/zhboner/realm
#
# Thanks: Teddysun <i@teddysun.com>
FROM alpine:latest
LABEL maintainer="5points"

ARG TARGETPLATFORM
WORKDIR /root
COPY alpine-realm.sh /root/alpine-realm.sh
COPY realm-server.toml /etc/realm/realm-server.toml

RUN set -ex \
	&& runDeps="curl wget ca-certificates jq tar" \
	&& apk add --update --no-cache --virtual .build-deps ${runDeps} \
        && apk add --update --no-cache tzdata \
	&& update-ca-certificates \
	&& chmod +x /root/alpine-realm.sh \
	&& /root/alpine-realm.sh "${TARGETPLATFORM}" \
	&& rm -fv /root/alpine-realm.sh \
	&& apk del .build-deps

WORKDIR /usr/bin/
ENV TZ=Asia/Hong_Kong
EXPOSE 6060/tcp 6060/udp

ENTRYPOINT ["/usr/bin/realm"]
